### ISSUE TITLE
Normalize weights not needed for Loihi

### ISSUE THREAD

**Issue by jimzhou112** [NeuromorphicProcessorProject/snn_toolbox#110]
Hello,

I noticed that for your INIsimulator example, the config file contains normalize = True. Setting it to be false would cause accuracy degradation. However, this normalization is not necessary for deployment on Loihi to achieve good accuracy. I noticed that there is a comment that states normalization is not needed for Loihi backend, as seen below.

config['tools'] = {
    'evaluate_ann': True,           # Test ANN on dataset before conversion.
    'normalize': False              # Not needed for Loihi backend.
}

Could you explore a little more in-depth why normalization is not necessary for the Loihi backend only? It seems Loihi performs very well without it.

**Comment by rbodo** [comment]
The reason is simply that NxTF (the compiler that the toolbox uses to map a network to Loihi) already applies some form of parameter normalization (see Sec. 2.3.7 in [this paper](https://arxiv.org/pdf/2101.04261.pdf)). It doesn't hurt to do it in the toolbox as well, but there is no benefit to be expected.
