### ISSUE TITLE
A question about the input current equation in the paper

### ISSUE THREAD

**Issue by ljxgit** [NeuromorphicProcessorProject/snn_toolbox#28]
Hi, rbodo,
I read your paper "Conversion of Continuous-Valued Deep Networks to Efficient Event-Driven Networks for Image Classification", I'm confused that why the input current of SNN neuron is the Vthr multiply the linear weighted sum item?
![image](https://user-images.githubusercontent.com/23187207/49911392-3bc96e00-fec1-11e8-9512-07111b670145.png)
Why not only the linear weighted sum?

Thanks

**Comment by rbodo** [comment]
It has to do with the normalization. We normalized the weights of each layer such that the ANN activations usually do not exceed 1. That means, the weighted sum above is usually smaller than 1. In the SNN, each neuron has a threshold. Imagine as an extreme case that this threshold is 1000. Then it will take 1000 time steps even for the largest input (1) to excite a neuron to fire a single spike, which effectively reduces the spikerate by a factor of 1000. So we scale the input by the threshold here to get a one-to-one correspondence between ANN activations and SNN spikerates.

In practice however, we set the threshold to 1 anyways, so it does not matter.

**Comment by ljxgit** [comment]
Thanks, rbodo, I got it
I want to ask one more question, I run the example program for the BinaryConnect, and I set the "binarize_weights = True" in the config file, why the weights are still in a real number range?
![image](https://user-images.githubusercontent.com/23187207/50008632-c27c6900-ffef-11e8-952e-124e020095c4.png)
Thanks rbodo!

**Comment by rbodo** [comment]
The reason is that the BinaryConnect architecture proposed by Courbariaux et al. uses BatchNormalization layers between Convolution and Activation layers. So after the ConvLayer weights have been binarized, The BatchNorm layers perform a linear transformation on the weights of each channel of the ConvLayer. That's why you get 128 different real numbers in the histogram. 
Their paper does not talk about this, but the weights are in fact not really binary at all because of the BatchNorm transformation....
