### ISSUE TITLE
About the accuracy of BinaryNet on cifar10

### ISSUE THREAD

**Issue by YiZhangNUDT** [NeuromorphicProcessorProject/snn_toolbox#33]
Hi rboda,
Thanks for your wonderful toolbox.
I tried the example about BinaryNet on cifar-10 and INI simulator. But the accuracy is quite low and different with your paper.  
The toolbox output is as follow.
//////////////////////////////////////////////////////////////////////////////////////////////////////////
Batch 2 of 2 completed (100.0%)
Moving accuracy of SNN (top-1, top-1): 5.00%, 10.00%.
Moving accuracy of ANN (top-1, top-1): 5.00%, 65.00%.
Simulation finished.
Total accuracy: 5.00% on 20 test samples.
/////////////////////////////////////////////////////////////////////////////////////////////////////////

And I used the example config downloaded from github.

Could you kindly help me to find the reason? I am looking for your reply.

Yi

**Comment by rbodo** [comment]
Hi Yi,

Another user reported this issue recently: #32 

The fact that the ANN top-1 accuracy is as bad as for the SNN indicates that the problem lies not in the conversion to SNN, but already in reading the input model (the "parsing" step in the pipeline). Since the input model is written in the Lasagne framework, my guess is that there has been an update in Lasagne that is not reflected in the toolbox (I have not worked with Lasagne input networks for over a year). Unfortunately, I won't be able to work on this myself any time soon. You could ask @sms821 if they found a solution by now.

**Comment by YiZhangNUDT** [comment]
Hi rboda,
Thanks for your kind reply.
I give a message to @sms821 but have not got the reply yet.
The version of Lasagne and Theano is 0.2.dev1 and 0.8.0. Could you use the lasagne-0.1 for the example before? If so, I will try to change the version.

**Comment by rbodo** [comment]
Yes, I remember having used lasagne version 0.1 before. Hopefully this solves it.
