### ISSUE TITLE
[question] load keras with custom_objects

### ISSUE THREAD

**Issue by bjuergens** [NeuromorphicProcessorProject/snn_toolbox#50]
I'm trying to convert an Keras ANN, which uses custom_objects. The custom_objects are two custom layers, and one custom initializer. As far as I can tell this is not yet possible with snn_toolbox. I have found [this](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/utils.py#L1230) function, which suggests that I can only use these pre-defined activations, and that I can't use custom initializers at all. 

You can find the definition of my custom_objects [here](https://github.com/spikingevolution/evolution-strategies/blob/7aa5456c90bac4583e2cbc120a87b0241e027153/load-model.py#L68). 

I intend to import my model into snn_toolbox by doing this: 

1. clone snn_toolbox
2. hard-code my own custom_objects into my version of snn_toolbox
3.  add the following after [this line](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/snntoolbox/parsing/model_libs/keras_input_lib.py#L129): <code>model = snntoolbox.utils.utils.apply_modifications(model, $my_custom_objects)</code>

### My questions for you

1. Do you think this approach can work?
2. Am I missing something here?

**Comment by rbodo** [comment]
Hi Bjoern,

Thanks for your detailed question.

You are right, the support for custom Keras objects is still a bit of a stump. What you propose should enable you to load the model, with a few caveats: 

- The [line you quote](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/model_libs/keras_input_lib.py#L129) is in a branch that is entered only when the model is saved as json file, with weights separate. This branch is there for backwards-compatibility for old Keras versions (pre v1), and I'm not even sure Keras still provieds this way of saving/loading models any more. So you could use the [second branch](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/model_libs/keras_input_lib.py#L138) (loading the h5 file with custom objects), by linking your custom objects in this [dict](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/utils.py#L1250) (despite its name, the function handles any custom objects, not just activations).
- If loading your model was successful, you still need to register these custom layers in the [config_default file](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/config_defaults#L129), otherwise the [parser will skip them](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/utils.py#L161). 
- Finally, (assuming you want to use these layers in the converted SNN), you should implement the spiking versions if those layers [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L552).

Good luck!
