### ISSUE TITLE
MNIST Spinnaker Example

### ISSUE THREAD

**Issue by Aashish3970** [NeuromorphicProcessorProject/snn_toolbox#67]
**When filing a bug, please provide:**
- A description of what you are trying to do
- Are you using the development or pypi version of the toolbox?
- The console output including the full stack trace
- Your config file

**Comment by Aashish3970** [comment]
Hello,
I tried using the MNIST keras spinnaker example https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_keras_spiNNaker.py. When I deploy this on spinnaker, the moving accuracy of ANN is 100% the moving accuracy of SNN is 0%. After that, I changed the simulation duration to 150 and v_thresh to 0.75. I am still getting the same accuracy. Plus, I get Average spike rate :0 spikes per simulation time step. What am I doing wrong?
![94970372-2a07ef00-04ca-11eb-89cd-fce63a4f7500](https://user-images.githubusercontent.com/54250712/94971808-828cbb80-04cd-11eb-9be0-0b9d0ac01242.png)


Below is my config file
![94970563-8b2fc280-04ca-11eb-81a6-b546d1887c2e](https://user-images.githubusercontent.com/54250712/94971797-79035380-04cd-11eb-9642-a65720624a83.png)

**Comment by rbodo** [comment]
Hi, I'm afraid I'll have to refer you with this issue to one of the SpiNNaker developers who were involved with this example (ej159, pabogdan). I currently don't have access to the hardware and cannot test this script myself. Sorry for not being able to help with this.

**Comment by Aashish3970** [comment]
Thanks for the reply. Does the toolbox create the PyNN code of the SNN and save it somewhere? How can I extract this SNN converted code ?

**Comment by rbodo** [comment]
The toolbox saves the pyNN projections here:
https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/2a64a9d6d97a5c203bd58c0d039eb7e63c07e80f/snntoolbox/simulation/target_simulators/spiNNaker_target_sim.py#L313
There will be a txt file for each layer containing its connections.

If you use the pyNN backend in the toolbox rather than SpiNNaker, it will also save the pyNN assemblies etc:
https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/2a64a9d6d97a5c203bd58c0d039eb7e63c07e80f/snntoolbox/simulation/target_simulators/pyNN_target_sim.py#L235

Maybe also take a look at the `load_assembly` method in that file, which reconstructs the layers from the saved files.

**Comment by Aashish3970** [comment]
Thanks a lot.
