### ISSUE TITLE
Force the use of a specific device

### ISSUE THREAD

**Issue by Narduzzi** [NeuromorphicProcessorProject/snn_toolbox#83]
Hello,

I am trying to simulate a Keras network. However, on GPU, the simulation results in an OOM error:

`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[59968,26,26,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ConcatV2] name: concat`

The error is probably due to the fact that my CNN allocates all the memory available on the GPU, and no more memory is available for the toolbox.

Is there a way to choose which device to be used for the simulation (CPU:0..., GPU:0, or GPU:1) ?
I am using the pypi version 0.5.0.

Thank you for helping!

**Comment by rbodo** [comment]
Hi Simon,

You can choose the device in the same way you would in a standalone Keras application, i.e. just put the line 

```os.environ["CUDA_VISIBLE_DEVICES"] = ""```

somewhere at the beginning of your script to switch to cpu, or specify the device id (e.g. `"0"`).

But I think the real problem is that you seem to be running the model on almost the entire dataset at once (the batch size appears to be 60'000 - 32). If that's not required for some reason, you might want to reduce it.

By the way, I'd recommend using the development version of the toolbox from github rather than pypi.

**Comment by Narduzzi** [comment]
Hello Bodo, 

Thank you for the trick. 
Indeed, I think I am using the entire training set for the normalization. Is there a way to reduce the batch size for normalization instead of reducing the dataset?

**Comment by rbodo** [comment]
I think that should be done by default in the development version. Let me know if it doesn't work

**Comment by rbodo** [comment]
Hi,

Sorry to hear that. In that case I don't know how to help you with setting the device then, it's not related to the toolbox.

Regarding batch size for normalization, please check that the batch size parameter is indeed set to some nonzero value [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/conversion/utils.py#L358) when running your code. If it is, then your memory issue might not be related to normalization at all.
