### ISSUE TITLE
Parsed model’s output not match to original model’s output

### ISSUE THREAD

**Issue by Umb1ife** [NeuromorphicProcessorProject/snn_toolbox#86]
Hello,

We convert MobileNetV2-SSD([Architecture](https://user-images.githubusercontent.com/46518324/110196837-819bf380-7e8a-11eb-8314-d7c8401ec2da.png)) to SNN, but the output of the parsed model output is different from the output of the original model (this difference is not as small as an error, completely different values).
When set config[‘tools’] = {‘normalize’: True} and convert a simple model like this, we could confirm the output of the parsed model and the original model matched.
```
# Simple Network
inputs = Input(shape=(32, 32, 3))

x = Conv2D(32, (3, 3), activation='relu')(inputs)
x = Conv2D(32, (3, 3), activation='relu')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)

x = Conv2D(32, (3, 3), activation='relu')(x)
x = Conv2D(32, (3, 3), activation='relu')(x)
x = MaxPooling2D(pool_size=(2, 2))(x)

x = Flatten()(x)
x = Dense(255, activation='relu')(x)
x = Dense(10, activation='softmax')(x)

x = Reshape((5, 2))(x)
x = Reshape((10,))(x)
```

I have questions about https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/fd843ec8b2c4c832a1c80c6709116e08e139a42f/snntoolbox/bin/utils.py#L93-L94
- What is the purpose of this normalize process ?
- If the network contains a structure that branches and integrates in the middle, will normalize be performed correctly ?

Thanks for your helping

**Comment by rbodo** [comment]
Hi,

The purpose of normalization is to make sure that the spikerates in each layer are neither too low nor too high. (The problem with low rates is approximation errors and loss of information due to spike rate quantization, and the problem of high rates is saturation at the maximum supported spike rate.) You can find more details in the [corresponding paper](https://www.frontiersin.org/articles/10.3389/fnins.2017.00682/full?report=reader).

Conversion of branched architectures should work, we have done it with ResNets and GoogleNet Inception V3. But your architecture looks a bit more complex still, so I can't guarantee the implementation is working as expected. A way to debug this is to start conversion with a single branch, test the parsed / normalized model still matches, and then add more and more branches, each time checking against the parsed model. (The accuracy would be useless here so you'd have to look at the layer activations.)

If you have the ability to train the model yourself, you could consider turning off normalization. To maintain accuracy in this case, the model should be trained with regularization / constraints on the activations to keep them in the range [0, 1] and encourage values close to 1.

But normalization is not the only reason why the parsed model might show an accuracy drop (BatchNorm layers, biases, special activation functions). You could check that by turning off normalization and checking if the accuracy of the parsed model still matches that of the original one.
