### ISSUE TITLE
example/mnist_keras_INI.py

### ISSUE THREAD

**Issue by moxueyingyan** [NeuromorphicProcessorProject/snn_toolbox#91]
Hello!
Thanks for your great contribution. The mnist_keras_INI.py runs successfully, and I find that the method init_neurons() is called in building spiking model, but some methods, e.g. update_neurons(), are not called in simulation.  I just want to see the change of membrane potential. 
I have questions:
Whether the generation of out_pikes in simulate() in INI_temporal_mean_rate_sim.py relates to membrane potential?
When and how the method update_neurons() should be called?

The environment:
snntoolbox0.6 tensorflow2.2 cuda11.0 
Thanks for your help!

**Comment by rbodo** [comment]
Hi,

The update_neurons function is wrapped into the decorator [`spike_call`](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L507), which is applied to each layer's [call method](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L648).

You might not see it being called during inference because it's part of the tf graph then. But it's definitely used. 

the `out_spikes` in `simulate()` do not represent the membrane potential but are the spikes you get when the membrane potential of neurons in the output layer crosses threshold. You can inspect the membrane potential e.g. by enabling the corresponding `plot_var` or `log_var`: #70

**Comment by moxueyingyan** [comment]
Hi,
Thank you for your timely reply! Previously I set breakpoints in init_neurons() function and update_neurons(), but it did not enter these functions, so I got it wrong. Maybe I should learn more about how Tensorflow graph runs. 
Now I try to plot some vars, e.g. v_mem, I find self._plot_keys in __init__() function in simulation/utils.py is None, 
However, the next line self._log_keys is correct.

I set breakpoints in the values, the result is as below:
self._plot_keys={set:0}set()
self._log_keys={set:4}{'spiketrains_n_b_l_t', 'mem_n_b_l_t', 'input_b_l_t', 'activations_n_b_l'}

I don't know what‘s wrong. How to modify the code?

the config in mnist_keras_INI.py as below:
config['output'] = {
    'log_vars': {
        'activations_n_b_l',
        'spiketrains_n_b_l_t',
        'input_b_l_t',
        'mem_n_b_l_t'},
    'plot_vars': {                  
        'spiketrains',              
        'spikerates',
        'activations',
        'correlation',
        'v_mem',
        'error_t'}
}

**Comment by rbodo** [comment]
The config looks correct. I've never seen this behavior before and am sorry that I can't help debugging, but you should be able to trace back why the plot_vars are empty using the debugger. Just to make sure, you did check that there are no plots being saved in the log/gui folder within the working directory? (The plots won't pop up, they are just saved to disk)

**Comment by moxueyingyan** [comment]
Thanks, rbodo!
When building spiking model, the membrane potential of each neuron in each layer has been computed by update_neurons() function and set_reset_mem() function in temporal_mean_rate_tensorflow.py. 
As described in Equation (3) and 4(b) in your paper "Conversion of Continuous-Valued Deep Networks to Efficient Event-Driven Networks for Image Classification", the membrane potential of each neuron changes with time.
However, I don't find the code corresponding to the process that the membrane potential changes v.s. time. I pay more attention to this process in my research. I don’t know if my understanding of membrane potential is correct. I hope you can give me some advice. Thank you!

**Comment by moxueyingyan** [comment]
I have another question:
As described in equation(2) in your paper, as below,
![input equation](https://user-images.githubusercontent.com/34503265/117635927-e5a4a600-b1b2-11eb-9eca-a6e5cee9fe32.png)
the input current changes with the step function indicating the occurrence of a spike at time t. However, I could not find the corresponding code. 
 The membrane potential is reseted by set_reset_mem() function after the output_spikes in update_neurons() function, but I don't know why the input current does not update at the same time, and I couldn't understand the input current in building spiking model very well. Can you help me? Thank you!

**Comment by rbodo** [comment]
> However, I don't find the code corresponding to the process that the membrane potential changes v.s. time. 

Here is how our builtin SNN simulator makes use of time: After converting a model, the model is run for a certain number of timesteps on each sample. This time loop can be found [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py#L151). Every timestep in this loop we do a forward pass of our model to propagate spikes through the network. Because the "call" function of each layer is decorated with the "update_neurons" function, the membrane potentials are updated at every timestep (or forward pass of the model).

Input spikes are added to the membrane potential in the `get_new_mem` method [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/1f1addab4caed15a63f416f40e8f983e05c23638/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py#L234). The `self.impulse` represents the `z` in Eq. 2.

**Comment by moxueyingyan** [comment]
Thanks a lot for the help！ Now I can use the code well. Thank you!
